AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: S3 Backed Lambda Email Forwarder for SES
Parameters:
  S3MarkersFile:
    Description: File location for markers.js
    Type: String
Resources:
  SesBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      LifecycleConfiguration:
        Rules:
        - ExpirationInDays: 3
          Status: Enabled
  WebBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: nc-tracker
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
  SesBucketPolicy:
      Type: "AWS::S3::BucketPolicy"
      Properties:
        Bucket:
          Ref: "SesBucket"
        PolicyDocument:
          Statement:
              Effect: Allow
              Principal:
                Service: ses.amazonaws.com
              Action: s3:PutObject
              Resource:
              - Fn::Join:
                - ''
                - - 'arn:aws:s3:::'
                  - Ref: SesBucket
                  - "/*"
              Condition:
                StringEquals:
                  aws:Referer:
                    Ref: AWS::AccountId
  LambdaSESACMForwarderRole:
    Type: AWS::IAM::Role
    DependsOn:
    - SesBucket
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: lambda-cloudwatch-access
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource:
            - "arn:aws:logs:*:*:*"
      - PolicyName: lambda-s3-access
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:GetObject
            Resource:
            - Fn::Join:
              - ''
              - - 'arn:aws:s3:::'
                - Ref: SesBucket
                - "/*"
      - PolicyName: lambda-s3-web-access
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:GetObject
            - s3:PutObject
            Resource:
            - Fn::Join:
              - ''
              - - 'arn:aws:s3:::'
                - Ref: WebBucket
                - "/*"
  SESACMForwarderLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../target/lambda.jar
      Handler: de.networkchallenge.handler.SesHandler::handleRequest
      Runtime: java8
      MemorySize: 256
      Timeout: 30
      Role:
        Fn::GetAtt:
        - LambdaSESACMForwarderRole
        - Arn
      Environment:
        Variables:
          SesBucketName:
            Ref: SesBucket
          WebBucketName:
            Ref: WebBucket
          MarkersFile:
            Ref: S3MarkersFile

Outputs:
  SesBucketName:
    Description: The bucket that stores SES ACM mail
    Value:
        Ref: SesBucket